import SpecialGreenFriedRice from '../assets/k1.png';
import GarlicChilliPrawn from '../assets/r1.png';
import GrilledPorkChops from '../assets/r2.png';

// export default [
const MenuList = [
    {   
        id: '1',
        type: 'Appetizers and Salads',
        name: 'Ru`s Special Trio',
        price: 9.95, 
        image:GrilledPorkChops,
    },
    {   
        id: '2',
        type: 'Appetizers and Salads',
        name: 'Herb Roasted Quail',
        price: 8.25,
        image: GarlicChilliPrawn,
    },
    {   
        id: '3',
        type: 'Appetizers and Salads',
        name: 'Crispy Salt and Pepper Calamari',
        price: 7.95,
        image: GarlicChilliPrawn,
    },
    {   
        id: '4',
        type: 'Appetizers and Salads',
        name: 'Homemade Style Crunchy Egg Rolls',
        price: 5.65,
        image: GarlicChilliPrawn,
    },
    {   
        id: '5',
        type: 'Appetizers and Salads',
        name: 'Wok-Tossed Baby Clam Served w/ Shrimp Chip',
        price: 9.95,
        image: GarlicChilliPrawn,
    },
    {   
        id: '6',
        type: 'Appetizers and Salads',
        name: 'Lemon Cured Shrimp Cabbage Salad',
        price: 9.95,
        image: GarlicChilliPrawn,
    },
    {   
        id: '7',
        type: 'Appetizers and Salads',
        name: 'Lotus Root Salad Topped w/ Shrimp & Pork',
        price: 8.75,
        image: GarlicChilliPrawn,
    },
    {   
        id: '8',
        type: 'Appetizers and Salads',
        name: 'Chicken Salad',
        price: 7.75,
        image: GarlicChilliPrawn,
    },
    {   
        id: '9',
        type: 'Pho - Beef Noodle Soup',
        name: 'Pho Combo w/ Rare Steak, Brisket, Tendon & Tripe',
        price: 10.75,
        image: GarlicChilliPrawn,
    },
    {   
        id: '10',
        type: 'Pho - Beef Noodle Soup',
        name: 'Rare Steak, Well-done Brisket and Tendon',
        price: 10.75,
        image: GarlicChilliPrawn,

    },
    {   
        id: '11',
        type: 'Pho - Beef Noodle Soup',
        name: 'Rare Steak, Well-done Brisket and Tripe',
        price: 10.75,
        image: GarlicChilliPrawn,
    },
    {   
        id: '12',
        type: 'Pho - Beef Noodle Soup',
        name: 'Rare Steak, Well-done Brisket and Meatballs',
        price: 10.75,
        image: GarlicChilliPrawn,
    },
    {   
        id: '13',
        type: 'Pho - Beef Noodle Soup',
        name: 'Rare Steak and Well-Done Brisket',
        price: 10.75,
        image: GarlicChilliPrawn,
    },
    {   
        id: '14',
        type: 'Pho - Beef Noodle Soup',
        name: 'Rare Steak and Beef Meatballs',
        price: 10.75,
        image: GarlicChilliPrawn,
    },
    {   
        id: '15',
        type: 'Pho - Beef Noodle Soup',
        name: 'Rare Steak',
        price: 10.75,
        image: GarlicChilliPrawn,
    },
    {   
        id: '16',
        type: 'Pho - Beef Noodle Soup',
        name: 'Pho with Chicken',
        price: 9.75,
        image: GarlicChilliPrawn,
    },
    {   
        id: '17',
        type: 'Pho - Beef Noodle Soup',
        name: 'Pho with Shrimps',
        price: 10.95,
        image: GarlicChilliPrawn,
    },
    {   
        id: '18',
        type: 'Pho - Beef Noodle Soup',
        name: 'Spicy Sate Pho',
        price: 10.75,
        image: GarlicChilliPrawn,
    },
    {   
        id: '19',
        type: 'Pho - Beef Noodle Soup',
        name: 'Pho w/ Rare Filet Mignon (Quarter Pound Tenderloin)',
        price: 11.95,
        image: GarlicChilliPrawn,
    },
    {   
        id: '20',
        type: 'Noodle Soups',
        name: 'Braised Duck Soup with Egg Noodle',
        price: 11.75,
        image: GarlicChilliPrawn,
    },
    {   
        id: '21',
        type: 'Noodle Soups',
        name: 'Wonton Spicy Sate Soup w/ Egg or Rice Noodle',
        price: 10.75,
        image: GarlicChilliPrawn,
    },
    {   
        id: '22',
        type: 'Noodle Soups',
        name: 'Thick Crab Soup q/ Tapioca Noodle or Udon',
        price: 10.95,
        image: GarlicChilliPrawn,
    },
    {   
        id: '23',
        type: 'Shareable Dishes',
        name: 'BoBo Butter Crunchy Beef',
        price: 11.95,
        image: GarlicChilliPrawn,
    },
    {   
        id: '24',
        type: 'Shareable Dishes',
        name: 'Lemon Grass Chicken',
        price: 11.45,
        image: GarlicChilliPrawn,
    },
    {   
        id: '25',
        type: 'Shareable Dishes',
        name: 'Citrus Butter Prawn (Whole)',
        price: 13.95,
        image: GarlicChilliPrawn,
    },
    {   
        id: '26',
        type: 'Shareable Dishes',
        name: 'Orange Glazed Crispy Shell Shrimp',
        price: 13.95,
        image: GarlicChilliPrawn,
    },
    {   
        id: '27',
        type: 'Shareable Dishes',
        name: 'Spicy Satay Squid',
        price: 11.95,
        image: GarlicChilliPrawn,
    },
    {   
        id: '28',
        type: 'Shareable Dishes',
        name: 'Crispy Garlic Rainbow Trout (Whole)',
        price: 21.00,
        image: GarlicChilliPrawn,
    },
    {   
        id: '29',
        type: 'Shareable Dishes',
        name: 'Herb-Braised Duck (Half)',
        price: 14.95,
        image: GarlicChilliPrawn,
    },
    {   
        id: '30',
        type: 'Shareable Dishes',
        name: 'Eggplant w/ Sweet & Sour Sauce',
        price: 0.00,
        image: GarlicChilliPrawn,
    },
    {   
        id: '31',
        type: 'Shareable Dishes',
        name: 'Green Bean & Mushreem w/ Sate Sauce',
        price: 0.00,
        image: GarlicChilliPrawn,
    },
    {   
        id: '32',
        type: 'Shareable Dishes',
        name: 'Green Bean & Mushroom w/ Sate Sauce',
        price: 0.00,
        image: GarlicChilliPrawn,
    },
    {
        id: '33',
        type: 'One Dish Meals',
        name: 'Special Green Fried Rice w/ Cornish Game Hen',
        price: 13.95, 
        image: SpecialGreenFriedRice
    },
    {
        id: '34',
        type: 'One Dish Meals',
        name: 'Green Fried Rice w/ Grilled Garlic Prawns',
        price: 12.95, 
        image: SpecialGreenFriedRice
    },
    {
        id: '35',
        type: 'One Dish Meals',
        name: 'Grilled Garlic Prawns & Pork Chop w/ Steamed Jasmine Rice',
        price: 10.95,
        image: GarlicChilliPrawn
    },
    {
        id: '36',
        type: 'One Dish Meals',
        name: 'Grilled Pork Chops w/ Steamed Jasmine Rice',
        price: 10.45, 
        image: GrilledPorkChops},
    {
        id: '37',
        type: 'One Dish Meals',
        name: 'Grilled Garlic Prawns & Pork Chop w/ Steamed Jasmine Rice',
        price: 10.95,
        image: GarlicChilliPrawn
    },
    {
        id: '38',
        type: 'Beverages',
        name: 'Iced Coffee - Vietnamese Dark Roast Coffee w/ Condensed Milk',
        price: 4.35,
        image: GarlicChilliPrawn,
    },
    {
        id: '39',
        type: 'Beverages',
        name: 'Soda Egg Milk',
        price: 4.89,
        image: GarlicChilliPrawn,
    },
    {
        id: '40',
        type: 'Beverages',
        name: 'Sparkling Mango Juice',
        price: 3.85,
        image: GarlicChilliPrawn,
    },
    {
        id: '41',
        type: 'Beverages',
        name: 'Thai Tea',
        price: 4.25,
        image: GarlicChilliPrawn,
    },
    {
        id: '42',
        type: 'Beverages',
        name: 'Passion Fruit w/ Chia',
        price: 3.85,
        image: GarlicChilliPrawn,
    },
    {
        id: '43',
        type: 'Beverages',
        name: 'Fresh Squeezed Orange Juice',
        price: 4.25,
        image: GarlicChilliPrawn,
    },
    {
        id: '44',
        type: 'Beverages',
        name: 'Soft Drinks (Coke, Sprite, Sunkist, etc.)',
        price: 1.85,
        image: GarlicChilliPrawn,
    }, 
    {
        id: '45',
        type: 'Beverages',
        name: 'Avacado Smoothie',
        price: 4.65,
        image: GarlicChilliPrawn,
    },
    {
        id: '46',
        type: 'Beverages',
        name: 'Might Mango Smoothie',
        price: 4.65,
        image: GarlicChilliPrawn,
    },
    {
        id: '47',
        type: 'Beverages',
        name: 'Strawberry Banana Smoothie',
        price: 4.65,
        image: GarlicChilliPrawn,
    },
    {
        id: '48',
        type: 'Beverages',
        name: 'Matcha Green Tea Smoothie',
        price: 4.65,
        image: GarlicChilliPrawn,
    },
    {
        id: '49',
        type: 'House Special Dessert',
        name: 'Pandan Caramel Flan',
        price: 3.95,
        image: GarlicChilliPrawn,
    }
];

export default MenuList;